[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "target-cpu=x86-64"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "target-cpu=i686"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "target-cpu=generic"]
